-- Adiciona os 22 comércios levantados próximos a escolas de Caraguatatuba
-- diretamente na tabela 'prospectos' já existente no Supabase.
-- Rode no SQL Editor do Supabase. Seguro rodar mais de uma vez (ON CONFLICT DO NOTHING:
-- se o id já existir, a linha é ignorada em vez de duplicar).

insert into prospectos (id, data) values ('escola-prox-001', '{"id": "escola-prox-001", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Martim de Sá", "tipo": "Padaria", "endereco": "Martim de Sá", "contato": "(12) 3883-5256", "avaliacao": 3.8, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-002', '{"id": "escola-prox-002", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Caraguatá", "tipo": "Padaria", "endereco": "R. Antônio Henrique de Mesquita, 80 - Jardim Casa Branca", "contato": "(12) 98857-5883", "avaliacao": 4.9, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-003', '{"id": "escola-prox-003", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Laticínios Litoral Norte", "tipo": "Mercadinho", "endereco": "Av. Pres. Castelo Branco - Martim de Sá", "contato": "(12) 3897-2717", "avaliacao": 4.2, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-004', '{"id": "escola-prox-004", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Shopping do Pão", "tipo": "Padaria", "endereco": "R. Benedita Mendes de Souza - Tingá", "contato": "(12) 3881-4142", "avaliacao": 4.4, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-005', '{"id": "escola-prox-005", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Trigo Real", "tipo": "Padaria", "endereco": "Av. Rio Grande do Norte, 1200 - Indaiá", "contato": "(12) 99138-5230", "avaliacao": 4.6, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-006', '{"id": "escola-prox-006", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Mercearia Beija Flor", "tipo": "Mercadinho", "endereco": "Av. Garça, 140 - Jardim Gaivotas", "contato": "", "avaliacao": 4.5, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-007', '{"id": "escola-prox-007", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Bar e Mercearia do Toninho", "tipo": "Mercadinho", "endereco": "Avenida Cardeal, 442 - Jardim Gaivotas", "contato": "(12) 3888-2470", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-008', '{"id": "escola-prox-008", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Supermercado Donato", "tipo": "Mercadinho", "endereco": "Av. Mal. Deodoro da Fonseca, 981 - Tingá", "contato": "(12) 3883-7942", "avaliacao": 3.8, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-009', '{"id": "escola-prox-009", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Santo Pão", "tipo": "Padaria", "endereco": "R. João Marcello, 285 - Estrela D''Alva", "contato": "(12) 3883-2329", "avaliacao": 4.5, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-010', '{"id": "escola-prox-010", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Esquina do Barranco", "tipo": "Padaria", "endereco": "Av. Cândida de Souza - Barranco Alto", "contato": "(12) 99242-4141", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-011', '{"id": "escola-prox-011", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Tida", "tipo": "Padaria", "endereco": "Al. Maranhão, 589 - Porto Novo", "contato": "(12) 99623-8308", "avaliacao": 3.8, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-012', '{"id": "escola-prox-012", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Casa dos Pães", "tipo": "Padaria", "endereco": "Rua Lagoinha, 12 - Travessão", "contato": "(12) 99734-1920", "avaliacao": 4.7, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-013', '{"id": "escola-prox-013", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Bar e Mercearia Diniz", "tipo": "Mercadinho", "endereco": "Al. Antônio Luís G. Câmara Coutinho - Porto Novo", "contato": "", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-014', '{"id": "escola-prox-014", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Supermercado Pereque", "tipo": "Mercadinho", "endereco": "Av. José Herculano, 270 - Travessão", "contato": "(12) 99617-7231", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-015', '{"id": "escola-prox-015", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Mercadinho Esteve", "tipo": "Mercadinho", "endereco": "Av. José da Costa Pinheiro Júnior, 383 - Jaraguá", "contato": "", "avaliacao": 4.2, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-016', '{"id": "escola-prox-016", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Vitória (Rio do Ouro)", "tipo": "Padaria", "endereco": "Rio do Ouro", "contato": "", "avaliacao": 4.0, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-017', '{"id": "escola-prox-017", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Nova Massaguaçu", "tipo": "Padaria", "endereco": "R. Irma Lucília - Massaguaçu", "contato": "(12) 3884-5472", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-018', '{"id": "escola-prox-018", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Confeitaria Mil Folhas", "tipo": "Padaria", "endereco": "R. Pesc. Manoel Marcondes Sodré, 29 - Massaguaçu", "contato": "(12) 3884-8898", "avaliacao": 4.3, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-019', '{"id": "escola-prox-019", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria Rocha", "tipo": "Padaria", "endereco": "R. Itália Baffi Magni - Massaguaçu", "contato": "(12) 97410-6739", "avaliacao": 4.0, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-020', '{"id": "escola-prox-020", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Padaria do Carmo", "tipo": "Padaria", "endereco": "Av. Arthur Costa Filho, 1821 - Centro", "contato": "(12) 98274-3333", "avaliacao": 4.2, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-021', '{"id": "escola-prox-021", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "ONO - Peixaria e Produtos Orientais", "tipo": "Mercadinho", "endereco": "Av. Dr. Arthur da Costa Filho, 1999 - Sumaré", "contato": "(12) 3881-1181", "avaliacao": 4.6, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
insert into prospectos (id, data) values ('escola-prox-022', '{"id": "escola-prox-022", "cidade": "Caraguatatuba", "prioridade": "Litoral", "nome": "Supermarket Canto Bravo", "tipo": "Mercadinho", "endereco": "R. Professora Adali Coelho Passos, 690 - Prainha", "contato": "(12) 3882-5265", "avaliacao": 4.2, "status": "Não contatado", "dataUltimoContato": "", "motivo": "", "obs": "Próximo a escola (raio de 500m) — origem: levantamento de escolas", "comercioId": null}'::jsonb) on conflict (id) do nothing;
